development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:fccebc9538e0ee416d6d60194bb9f5dc@cod.redistogo.com:10819/
  channel_prefix: slack_clone_production
